Neos:
  Flow:
    http:

      middlewares:
        'Flownative.OpenIdConnect.Client:setJwtCookie':
          position: 'after session'
          middleware: 'Flownative\OpenIdConnect\Client\Http\Middleware\SetJwtCookieMiddleware'

      chain:
        'postprocess':
          chain:
            'Flownative.OpenIdConnect.Client:setJwtCookie':
              'position': 'after setSessionCookie'
              component: 'Flownative\OpenIdConnect\Client\Http\SetJwtCookieComponent'
              componentOptions:
                authenticationProviderName: 'Flownative.OpenIdConnect.Client:OidcProvider'
                cookie:
                  name: 'flownative_oidc_jwt'
                  secure: true
                  sameSite: 'strict'
